### ISSUE TITLE
closes

### ISSUE THREAD

**Issue by openbeast90** [alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#11]
why does it close automaticly without setting up the bot

**Comment by alexjdesio** [comment]
This was most likely an issue caused by the bot previously using discord.io rather than discord.js. Please download the newest release of the bot from the main branch(released today!) and let me know if you encounter this issue again. In addition, the README now has a detailed section that should help you [get started](https://github.com/alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#getting-started).
