### ISSUE TITLE
Snipe command chooses bad items 

### ISSUE THREAD

**Issue by Andrelissss** [alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#14]
wither chetplate is 22m and it shows 42m and its flipable lmao

**Comment by alexjdesio** [comment]
Snipe chooses to display all items below the specified point to the user. You set the maximum amount you are willing to pay, and snipe will show you every listing below that price, as quickly as possible.

Example: Imagine Necron's Handle is trading for 350mil. If you could get one for less than 275mil, then you know you would immediately buy it. This would be a great item to use with snipe, setting your maximum price to 275mil because anything it shows you below that price point you will attempt to buy.

I took a look at the Wither Chestplate prices, it looks like the cheapest one is ~25mil and the cheapest 5star one is ~35mil. Most likely you have !snipe configured to search for 5star Wither Chestplates, if this is not the case you can remove "5star" from max_price and watchList and it should update to show you listings without stars.
