### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by lalinko** [alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#9]
So like can you make a youtube video of setting this up or invite me to ur discord server I wanna see how this works

**Comment by alexjdesio** [comment]
The bot is not dedicated/persistent, which means that when you are not actively running the program on your computer, the bot is not active. I can absolutely make a video for you so that you can see what the bot looks like in action. 

[Here is the link.](https://www.youtube.com/watch?v=eBy1llRyVyU)

Feel free to take a look at the README for more information on [how to get started](https://github.com/alexjdesio/Skyblock-Auctions-Analyzer-Discord-Bot#getting-started). Don't be afraid to post more questions here!
